version: '3'
services:
  nginx:
    build:
      dockerfile: docker/nginx/Dockerfile
      context: .
    ports:
     - 80:80
     - 443:443
    volumes:
      - './docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro'
      - './data/certbot/conf:/etc/letsencrypt'
      - './data/certbot/www:/var/www/certbot'
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  
  certbot:
    image: certbot/certbot
    volumes:
      - './data/certbot/conf:/etc/letsencrypt'
      - './data/certbot/www:/var/www/certbot'
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  
  react:
    build:
      dockerfile: docker/react/Dockerfile
      context: .
    ports:
      - 3000:3000
    volumes:
      - ".:/app"
      - "/app/node_modules"
    environment:
      - NODE_ENV=development
