version: '3'
services:
  web:
    build:
      dockerfile: docker/nginx/Dockerfile
      context: .
    ports:
     - "8080:80"
    volumes:
      - './docker/nginx/root/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro'
      - './data/certbot/conf:/etc/letsencrypt'
      - './data/certbot/www:/var/www/certbot'
    
  react:
    build:
      dockerfile: docker/react/Dockerfile
      context: .
    ports:
      - 3000:3000
    volumes:
      - ".:/app"
      - "/app/node_modules"
    environment:
      - NODE_ENV=development
