version: '3'
services:
  nginx:
    build:
      dockerfile: docker/nginx/Dockerfile
      context: .
    ports:
     - 10080:80
    volumes:
      - './docker/nginx/conf.d/defaultdev.conf:/etc/nginx/conf.d/default.conf:ro'
    
  react:
    build:
      dockerfile: docker/react/Dockerfile
      context: .
    ports:
      - 3000:3000
    volumes:
      - ".:/app"
      - "/app/node_modules"
    environment:
      - NODE_ENV=development